# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b787a987aa76238745fcb55c9735a34c9dafe93f0ecadf65f274a06364dd3c3e09d13e4cba96b66a563179a0b218afdc26d43ff7d0f629ff5ec71dc96406e35d

test:
  secret_key_base: 9b9bb778f0377aad45a2726fab890052f1c31009201dc73d28f9af34893cd01a4ad964e82105d96ffd8295096316a2caa5b42d39347c3b86cc18af5df3413bce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
